// Mã JavaScript tương đương với TypeScript

// Kiểu dữ liệu cho Json
const Json = ["string", "number", "boolean", "null", "object", "array"];

// Định nghĩa cấu trúc cơ sở dữ liệu
const Database = {
  public: {
    Tables: {
      customers: {
        Row: {
          id: "",
          stripe_customer_id: null,
        },
        Insert: {
          id: "",
          stripe_customer_id: null,
        },
        Update: {
          id: undefined,
          stripe_customer_id: null,
        },
      },
      liked_songs: {
        Row: {
          song_id: 0,
          user_id: "",
        },
        Insert: {
          song_id: 0,
          user_id: "",
        },
        Update: {
          song_id: undefined,
          user_id: undefined,
        },
      },
      prices: {
        Row: {
          active: null,
          currency: null,
          description: null,
          id: "",
          interval: null,
          interval_count: null,
          metadata: null,
          product_id: null,
          trial_period_days: null,
          type: null,
          unit_amount: null,
        },
        Insert: {
          active: null,
          currency: null,
          description: null,
          id: "",
          interval: null,
          interval_count: null,
          metadata: null,
          product_id: null,
          trial_period_days: null,
          type: null,
          unit_amount: null,
        },
        Update: {
          active: null,
          currency: null,
          description: null,
          id: undefined,
          interval: null,
          interval_count: null,
          metadata: null,
          product_id: null,
          trial_period_days: null,
          type: null,
          unit_amount: null,
        },
      },
      products: {
        Row: {
          active: null,
          description: null,
          id: "",
          image: null,
          metadata: null,
          name: null,
        },
        Insert: {
          active: null,
          description: null,
          id: "",
          image: null,
          metadata: null,
          name: null,
        },
        Update: {
          active: null,
          description: null,
          id: undefined,
          image: null,
          metadata: null,
          name: null,
        },
      },
      songs: {
        Row: {
          author: null,
          created_at: null,
          id: 0,
          image_path: null,
          song_path: null,
          title: null,
          user_id: null,
        },
        Insert: {
          author: null,
          created_at: null,
          id: undefined,
          image_path: null,
          song_path: null,
          title: null,
          user_id: null,
        },
        Update: {
          author: null,
          created_at: null,
          id: undefined,
          image_path: null,
          song_path: null,
          title: null,
          user_id: null,
        },
      },
      subscriptions: {
        Row: {
          cancel_at: null,
          cancel_at_period_end: null,
          canceled_at: null,
          created: "",
          current_period_end: "",
          current_period_start: "",
          ended_at: null,
          id: "",
          metadata: null,
          price_id: null,
          quantity: null,
          status: null,
          trial_end: null,
          trial_start: null,
          user_id: "",
        },
        Insert: {
          cancel_at: null,
          cancel_at_period_end: null,
          canceled_at: null,
          created: "",
          current_period_end: "",
          current_period_start: "",
          ended_at: null,
          id: "",
          metadata: null,
          price_id: null,
          quantity: null,
          status: null,
          trial_end: null,
          trial_start: null,
          user_id: "",
        },
        Update: {
          cancel_at: null,
          cancel_at_period_end: null,
          canceled_at: null,
          created: "",
          current_period_end: "",
          current_period_start: "",
          ended_at: null,
          id: undefined,
          metadata: null,
          price_id: null,
          quantity: null,
          status: null,
          trial_end: null,
          trial_start: null,
          user_id: "",
        },
      },
      users: {
        Row: {
          avatar_url: null,
          billing_address: null,
          full_name: null,
          id: "",
          payment_method: null,
        },
        Insert: {
          avatar_url: null,
          billing_address: null,
          full_name: null,
          id: "",
          payment_method: null,
        },
        Update: {
          avatar_url: null,
          billing_address: null,
          full_name: null,
          id: undefined,
          payment_method: null,
        },
      },
    },
    Views: {},
    Functions: {},
    Enums: {
      pricing_plan_interval: ["day", "week", "month", "year"],
      pricing_type: ["one_time", "recurring"],
      subscription_status: [
        "trialing",
        "active",
        "canceled",
        "incomplete",
        "incomplete_expired",
        "past_due",
        "unpaid",
      ],
    },
    CompositeTypes: {},
  },
};

// Xuất các kiểu dữ liệu cho việc sử dụng sau này, nếu cần
module.exports = { Json, Database };